/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Image;
import java.io.File;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import motor.MasterMindEngine;
import motor.RegistroNota;

/**
 *
 * @author mstrv
 */
public class MasterMindV4_0 extends javax.swing.JFrame {
    private static ImageIcon favicon;
    private static MasterMindEngine juego;
    
    /**
     * Creates new form MasterMindV4_0
     */
    public MasterMindV4_0() {
        initComponents();
        favicon= new ImageIcon(getClass().getResource("/main_icon.png"));
        this.setIconImage(favicon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        campoCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaHistorial = new javax.swing.JTextPane();
        botonOK = new javax.swing.JButton();
        campoBuenos = new javax.swing.JTextField();
        campoRegulares = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioAdivinador = new javax.swing.JRadioButton();
        radioPensador = new javax.swing.JRadioButton();
        botonIniciar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MasterMind 4.0");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 51, 0));

        campoCodigo.setEditable(false);
        campoCodigo.setBackground(new java.awt.Color(0, 51, 51));
        campoCodigo.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        campoCodigo.setForeground(new java.awt.Color(51, 255, 0));
        campoCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoCodigo.setText("...");
        campoCodigo.setToolTipText("En modo ADIVINADOR ingresa aquí tu código; en modo PENSADOR se mostrará aquí el código presentado por MasterMind.");
        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("B=");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("R=");

        areaHistorial.setEditable(false);
        areaHistorial.setBorder(javax.swing.BorderFactory.createTitledBorder("Historial"));
        areaHistorial.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        areaHistorial.setForeground(new java.awt.Color(0, 51, 51));
        jScrollPane1.setViewportView(areaHistorial);

        botonOK.setBackground(new java.awt.Color(0, 153, 0));
        botonOK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonOK.setText("OK");
        botonOK.setEnabled(false);
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        campoBuenos.setBackground(new java.awt.Color(0, 51, 51));
        campoBuenos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        campoBuenos.setForeground(new java.awt.Color(255, 255, 255));
        campoBuenos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoBuenos.setText("0");
        campoBuenos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoBuenosFocusGained(evt);
            }
        });
        campoBuenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuenosActionPerformed(evt);
            }
        });

        campoRegulares.setBackground(new java.awt.Color(0, 51, 51));
        campoRegulares.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        campoRegulares.setForeground(new java.awt.Color(255, 255, 255));
        campoRegulares.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoRegulares.setText("0");
        campoRegulares.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoRegularesFocusGained(evt);
            }
        });
        campoRegulares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRegularesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(campoCodigo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBuenos, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoRegulares, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoBuenos)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoRegulares))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Modo de Juego");

        radioAdivinador.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioAdivinador);
        radioAdivinador.setSelected(true);
        radioAdivinador.setText("Adivinador");

        radioPensador.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioPensador);
        radioPensador.setText("Pensador");

        botonIniciar.setBackground(new java.awt.Color(0, 102, 0));
        botonIniciar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        botonIniciar.setText("Iniciar juego");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(255, 0, 0));
        botonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonCancelar.setBackground(new java.awt.Color(0, 0, 0));
        botonCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setText("Cancelar");
        botonCancelar.setEnabled(false);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioPensador)
                                    .addComponent(radioAdivinador))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(botonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioAdivinador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioPensador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * Toma el texto del campo de ingreso de códigos y evalúa si el mismo cumple
     * con los requisitos para ser un código válido. En caso negativo se muestra
     * el mensaje de error corresondiente, en caso afirmativo se presenta el código
     * al juego para que sea evaluado y, en consecuencia, se realicen las acciones
     * pertinentes: avanzar intentos, cambiar el estado a GANO o PERDIO, etc.
     */
    public void eventoLeerCodigo(){
        StringBuilder errorMessage= new StringBuilder();
        RegistroNota resultadoEvaluacion;
        
        if("".equals(campoCodigo.getText())) return;
        char[] adivinador= campoCodigo.getText().toUpperCase().toCharArray();
        if (MasterMindEngine.evaluarCodigo(adivinador,errorMessage)){
            resultadoEvaluacion= juego.presentarCodigo(adivinador);
            if (juego.obtenerEstado()==MasterMindEngine.EstadoJuego.GANO ){
                JOptionPane.showMessageDialog(this, "¡¡¡GANASTE!!!","Felicitaciones",JOptionPane.INFORMATION_MESSAGE);
                campoCodigo.setEditable(false);
                botonOK.setEnabled(false);
                radioAdivinador.setEnabled(true);
                radioPensador.setEnabled(true);
                botonIniciar.setEnabled(true);
                botonCancelar.setEnabled(false);
            }else if(juego.obtenerEstado()==MasterMindEngine.EstadoJuego.PERDIO){
                JOptionPane.showMessageDialog(this, "¡¡¡PERDISTE!!! El código era "+juego.obtenerCodigoPensador(),"Una verdadera lástima",JOptionPane.INFORMATION_MESSAGE);
                campoCodigo.setEditable(false);
                botonOK.setEnabled(false);
                radioAdivinador.setEnabled(true);
                radioPensador.setEnabled(true);
                botonIniciar.setEnabled(true);
                botonCancelar.setEnabled(false);
            }else{
                areaHistorial.setText(areaHistorial.getText()+juego.obtenerIntento()+") "
                        + campoCodigo.getText().toUpperCase()+" --> "
                        + "B= "+resultadoEvaluacion.obtenerBuenos()+" y "
                        + "R= "+resultadoEvaluacion.obtenerRegulares()+"\n");
                campoCodigo.setText("");
                campoBuenos.setText(Integer.toString(resultadoEvaluacion.obtenerBuenos()));
                campoRegulares.setText(Integer.toString(resultadoEvaluacion.obtenerRegulares()));
            }
        }else{
            JOptionPane.showMessageDialog(this, errorMessage,"Estás haciendo algo mal",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void eventoLeerNotas(){
        StringBuilder errorMessage= new StringBuilder();
        RegistroNota resultadoEvaluacion;
        int buenos, regulares;
        
        String strB= campoBuenos.getText(), strR= campoRegulares.getText();
        try{
            buenos= Integer.parseInt(strB);
            regulares= Integer.parseInt(strR);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"ERROR: Debes ingresar números enteros.","Estás haciendo algo mal",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!MasterMindEngine.evaluarNotas(buenos, regulares, errorMessage)){
            JOptionPane.showMessageDialog(this, errorMessage,"Estás haciendo algo mal",JOptionPane.ERROR_MESSAGE);
        }else{
            resultadoEvaluacion= juego.presentarNotas(buenos, regulares, juego.obtenerCodigoAdivinador().toCharArray());
            if (juego.obtenerEstado()==MasterMindEngine.EstadoJuego.GANO ){
                JOptionPane.showMessageDialog(this, "¡¡¡GANASTE!!!","Felicitaciones",JOptionPane.INFORMATION_MESSAGE);
                campoBuenos.setEditable(false);
                campoRegulares.setEditable(false);
                botonOK.setEnabled(false);
                radioAdivinador.setEnabled(true);
                radioPensador.setEnabled(true);
                botonIniciar.setEnabled(true);
            }else if(juego.obtenerEstado()==MasterMindEngine.EstadoJuego.PERDIO){
                JOptionPane.showMessageDialog(this, "¡¡¡PERDISTE!!! Pónmelo más difícil.","Una verdadera lástima",JOptionPane.INFORMATION_MESSAGE);
                campoCodigo.setEditable(false);
                botonOK.setEnabled(false);
                radioAdivinador.setEnabled(true);
                radioPensador.setEnabled(true);
                botonIniciar.setEnabled(true);
                botonCancelar.setEnabled(false);
            }else if (juego.obtenerEstado()==MasterMindEngine.EstadoJuego.TRAMPA){
                JOptionPane.showMessageDialog(this, "¡¡¡ESTÁS HACIENDO TRAMPA!!! ¿Qué tu integridad es tan débil?","Cobarde",JOptionPane.ERROR_MESSAGE);
                campoCodigo.setEditable(false);
                botonOK.setEnabled(false);
                radioAdivinador.setEnabled(true);
                radioPensador.setEnabled(true);
                botonIniciar.setEnabled(true);
                botonCancelar.setEnabled(false);
            }else{
                areaHistorial.setText(areaHistorial.getText()+juego.obtenerIntento()+") "
                        + campoCodigo.getText().toUpperCase()+" --> "
                        + "B= "+resultadoEvaluacion.obtenerBuenos()+" y "
                        + "R= "+resultadoEvaluacion.obtenerRegulares()+"\n");
                campoCodigo.setText(new String(juego.siguienteAdecuado()));
                campoBuenos.setText(Integer.toString(resultadoEvaluacion.obtenerBuenos()));
                campoRegulares.setText(Integer.toString(resultadoEvaluacion.obtenerRegulares()));
                campoBuenos.requestFocus();
            }
        }
        
    }
    
    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        if (radioAdivinador.isSelected()){
            juego= new MasterMindEngine(MasterMindEngine.ModoJuego.ADIVINADOR);
            campoCodigo.setEnabled(true);
            campoCodigo.setEditable(true);
            campoCodigo.setText("");
            campoBuenos.setEditable(false); campoBuenos.setEnabled(true);
            campoBuenos.setText("0"); 
            campoRegulares.setEditable(false); campoRegulares.setEnabled(true);
            campoRegulares.setText("0");
            botonOK.setEnabled(true);
            areaHistorial.setText("Dispones de "+MasterMindEngine.MAX_INTENTOS+" intentos:\n");
            botonCancelar.setEnabled(true);
            campoCodigo.requestFocus();
        }else{
            juego= new MasterMindEngine(MasterMindEngine.ModoJuego.PENSADOR);
            campoCodigo.setEnabled(true);
            campoCodigo.setEditable(false);
            campoCodigo.setText(juego.obtenerCodigoAdivinador());
            campoBuenos.setEditable(true); campoBuenos.setEnabled(true);
            campoBuenos.setText("0");
            campoRegulares.setEditable(true); campoRegulares.setEnabled(true);
            campoRegulares.setText("0");
            botonOK.setEnabled(true);
            botonCancelar.setEnabled(true);
            areaHistorial.setText("Dispones de "+MasterMindEngine.MAX_INTENTOS+" intentos:\n");
            campoBuenos.requestFocus();
        }
        
        radioAdivinador.setEnabled(false);
        radioPensador.setEnabled(false);
        botonIniciar.setEnabled(false);
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        eventoLeerCodigo();
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        if(juego.obtenerModo()==MasterMindEngine.ModoJuego.ADIVINADOR){
            eventoLeerCodigo();
        }else{
            eventoLeerNotas();
        }
    }//GEN-LAST:event_botonOKActionPerformed

    private void campoBuenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuenosActionPerformed
        eventoLeerNotas();
    }//GEN-LAST:event_campoBuenosActionPerformed

    private void campoRegularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRegularesActionPerformed
        eventoLeerNotas();
    }//GEN-LAST:event_campoRegularesActionPerformed

    private void campoBuenosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBuenosFocusGained
        campoBuenos.selectAll();
    }//GEN-LAST:event_campoBuenosFocusGained

    private void campoRegularesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRegularesFocusGained
        campoRegulares.selectAll();
    }//GEN-LAST:event_campoRegularesFocusGained

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        juego= null;
        campoCodigo.setText("");
        campoCodigo.setEnabled(false);
        campoBuenos.setText("");
        campoBuenos.setEnabled(false);
        campoRegulares.setText("");
        campoRegulares.setEnabled(false);
        botonOK.setEnabled(false);
        radioAdivinador.setEnabled(true);
        radioPensador.setEnabled(true);
        botonIniciar.setEnabled(true);
        botonCancelar.setEnabled(false);
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterMindV4_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterMindV4_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterMindV4_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterMindV4_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterMindV4_0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane areaHistorial;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonOK;
    private javax.swing.JButton botonSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoBuenos;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoRegulares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioAdivinador;
    private javax.swing.JRadioButton radioPensador;
    // End of variables declaration//GEN-END:variables
}
